### ISSUE TITLE
Add Topics Metadata

### ISSUE THREAD

**Issue by DaTebe** [FraunhoferISST/diva#106]
**Is your feature request related to a problem? Please describe.**
For a better search and find ability, the entities should have a topic attribute. The topics should be predefined (e.g. `science`, `city`, `financial`, ...)

**Describe the solution you'd like**
We can extend our JSON schema with a new attribute. It could be an enumeration. We should discuss, how easy topics can be extended from the user perspective. If we allow arbitrary topics, this would be like our `keywords` fields. It should be possible to have multiple topics per resource.

**Comment by DaTebe** [comment]
We should take a look at available vocabularies: https://joinup.ec.europa.eu/release/dcat-ap-how-use-mdr-data-themes-vocabulary

**Comment by DaTebe** [comment]
<html>
<body>


Agriculture and Fisheries | http://publications.europa.eu/resource/authority/data-theme/AGRI
-- | --
Culture and Sports | http://publications.europa.eu/resource/authority/data-theme/EDUC
Economy and Finance | http://publications.europa.eu/resource/authority/data-theme/ECON
Education | http://publications.europa.eu/resource/authority/data-theme/EDUC
Energy | http://publications.europa.eu/resource/authority/data-theme/ENER
Environment | http://publications.europa.eu/resource/authority/data-theme/ENVI
Health | http://publications.europa.eu/resource/authority/data-theme/HEAL
International | http://publications.europa.eu/resource/authority/data-theme/INTR
Justice | http://publications.europa.eu/resource/authority/data-theme/JUST
Population | http://publications.europa.eu/resource/authority/data-theme/SOCI
Public Sector | http://publications.europa.eu/resource/authority/data-theme/GOVE
Regional | http://publications.europa.eu/resource/authority/data-theme/REGI
Science and Technology | http://publications.europa.eu/resource/authority/data-theme/TECH
Transport


</body>
</html>

**Comment by Cl-Ti** [comment]
From our experience in working with german cities we very much support the featrue request 

examples often given to us are the categories of the well known open data portals like https://data.gov.sg/  

to check whether other categories are also relevant for internal data. For example, in cities one works with the so-called "Fachverfahren". Perhaps it should be checked here whether these are relevant tags or even the offices of a city should be listed as a category.

**Comment by DaTebe** [comment]
I've added a table of topics at the top. We can think about merging duplicates and also collect more ideas.

**Comment by DaTebe** [comment]
One additional note: if we stick to these `themes` it could be easier to harvest existing open data portals in the future.

**Comment by DaTebe** [comment]
This is a proposal for our `themes` field containing predefined values. 

Pros:

- super easy implementation
- easy search and filtering

Cons:

- we can not change the naming of themes without a migration path
- multi language will be more difficult

```
"themes": {
      "$id": "themes",
      "type": "array",
      "title": "Themes",
      "description": "Predefined themes of the entity",
      "default": [],
      "minItem": 0,
      "items": {
        "$id": "themes/items/",
        "type": "string",
        "enum": [
          "Agriculture",
          "Culture",
          "Economy",
          "Education",
          "Energy",
          "Environment",
          "Finance",
          "Fisheries",
          "Health",
          "Infrastructure",
          "International",
          "Justice",
          "Population",
          "Public Sector",
          "Regional",
          "Science",
          "Society",
          "Sports",
          "Technology",
          "Transport"
        ],
        "title": "Theme Items",
        "description": "A theme",
        "_elasticsearch": {
          "type": "keyword"
        }
      }
    }
```

**Comment by DaTebe** [comment]
@setaman does it make sense to add `themes` to these booster list on search? https://github.com/FraunhoferISST/diva/blob/e5ead38d872d9b680c0a665bcec6662f65981b06/core/services/search-assistant/services/SearchService.js#L31

**Comment by setaman** [comment]
@DaTebe i think, should be fine to boost it with 2 or 3

**Comment by Cl-Ti** [comment]
> One additional note: if we stick to these `themes` it could be easier to harvest existing open data portals in the future.

I like the idea - this could be interesting in future
