### ISSUE TITLE
Add "location" to properties

### ISSUE THREAD

**Issue by DaTebe** [FraunhoferISST/diva#109]
**Is your feature request related to a problem? Please describe.**
Sometimes, entities have a location in form of a point(s) or polygon(s). E.g. a resource can be about a specific city or a POI. We want users to be able to set such a location. Also we should render a map in our web client to show the location. This feature is prominent in Open Data Portals. We should not try to invent something new. It seems the ODP solutions work just fine here.

**Describe the solution you'd like**
We need to add a new property which can store the location information. We need to do some research in best practice of storing such locations.

**Additional context/tasks**

- [x] look into vocabularies like DCAT-AP
- [x] look for an map plugin for vuejs (e.g with open street map) -> https://vue2-leaflet.netlify.app/quickstart/

It seems that `vue2-leaflet` will do the job. We need to discuss which kind of location data we want to support. It seems that the library supports: `points`, `circles`, `rectangles`, `polygons `and `polylines`. A lot of drag and drop inside the map is available which should make the interaction with the user much more easy.

**Comment by DaTebe** [comment]
We can use this JSON schema that is build around the GeoJSON specification: https://github.com/fge/sample-json-schemas/blob/master/geojson/geometry.json

**Comment by DaTebe** [comment]
Now going to use: https://json.schemastore.org/geojson.json ina n `location` field.

**Comment by DaTebe** [comment]
This is how the location field could look like. This is a non working mockup. 

![IMG-20211120-WA0012](https://user-images.githubusercontent.com/12967305/142731522-729898d5-7cc4-4aa5-849c-10e5752ce3c2.jpg)

**Comment by DaTebe** [comment]
We are now able to edit the `location` property using the visual tools.

**Comment by DaTebe** [comment]
@setaman do we want to implement an `expert` mode? Or do we want to have this feature as part of a global JSON metadata editor?

**Comment by setaman** [comment]
@DaTebe 
difficult to evaluate the importance of this feature and how common is that someone want to copy and paste geojson locations. Not sure that the metadata editor will come soon.  So if the expert mode is required, we should add it now

**Comment by DaTebe** [comment]
Then let us put it on our "maybe" list and finish this issue.
