### ISSUE TITLE
Disclose login page for not authenticated users

### ISSUE THREAD

**Issue by setaman** [FraunhoferISST/diva#15]
**Describe the bug**

Although the login page is publicly accessible, after the authorization with Keycloak and the redirect to the client, the authentication errors may occur (e.g. token not valid). In this case, the user remains logged in to Keycloak, but cannot use the client. Moreover, logging in again or logging out is no longer possible.   

**To Reproduce**

1. Open client 
2. Bring some service down (UM or Kong)
3. Login through Keycloak
4. After redirect to client error is shown, authentication not possible
5. Client not usable

**Expected behavior**

We should at least provide the option to navigate to login page for another try or to log out 

**Additional context**

Most likely, the error will occur only in case of DIVA misconfiguration. In this case, nothing helps except contacting the administrator. Nevertheless, let's get rid of this limitation

**Comment by DaTebe** [comment]
Error would also occur on network errors. Should make it clean here.
