### ISSUE TITLE
Elasticsearch wrong Auto-Mapping

### ISSUE THREAD

**Issue by DaTebe** [FraunhoferISST/diva#16]
**Describe the bug**
When a document is added, a wrong auto mapping from elasticsearch can occur. This can lead to update/insert drops in the future. E.g. when a numeric value is detected as `int` or `long`, because the first value is a `1`. When a second document is added with a value of e.g. `0.92`, it will be rejected, as this would be of type float.

**To Reproduce**
1. Get a clean instance of elasticsearch
2. Add a document (e.g. a PDF file resource) with language `{"german": 1}`
3. Add a second document with language `{"dutch": 0.9}`

**Expected behavior**
Elasticsearch should accept the update/insert.

**Your environment(please complete the following information):**
 - DIVA version 2.2.0

**Additional context**

- We could provide a correct mapping before runtime.
- We could pre/postfix keys to prevent this kind of error.
- We could only store values where we are 100% sure they will be mapped correctly.

**Comment by setaman** [comment]
@DaTebe 

it appears, that ES has a difficulties to index a document that casually have a value for some field represented as `integer` and `float`. For example the following document:

```json
{
    "languages": [
        {
            "alpha3": "eng",
            "alpha2": "en",
            "language": "English",
            "score": 1
        },
        {
            "alpha3": "fra",
            "alpha2": "fr",
            "language": "French",
            "score": 0.856154
        }
    ]
}
```
This applies however only to Dynamic Mapping (fields are not already seen by ES). If the fields already have a mapping specified, the document will be indexed just fine. So we just have to put explicit mapping to our indices!

**Comment by DaTebe** [comment]
It's been a long time. We have now implemented a prototype that converts our JSON Schema to a Elasticsearch mapping.
See here: https://github.com/FraunhoferISST/diva/blob/13-optimize-search-experience/core/services/common/loadJsonSchema.js

And here: https://github.com/FraunhoferISST/diva/blob/13-optimize-search-experience/core/services/common/convertJsonSchema.js

It is possible to set a type inside the JSON Schema using our custom `_elasticsearch` field. It is also possible to set a specific analyser for text fields.

Implementation is specific to our way of using JSON Schemata. It may not work for all possible JSON Schemata.

We try to finish implementation till end of week.

**Comment by DaTebe** [comment]
@setaman now I've finished the simple solution: https://github.com/FraunhoferISST/diva/blob/71feaf4c833f08253f45a9479db2bb5079a8dcae/core/services/elasticsearch-connector/Connector.js#L49

Only put mapping when index not exists. This will be the case for the first startup of DIVA.

Now we need to discuss migration logic.
