### ISSUE TITLE
Search queries do not work with numbers

### ISSUE THREAD

**Issue by jbuese** [FraunhoferISST/diva#161]
**Describe the bug**
Search queries which include numbers do not work.
Affects every field where search-assistant / elasticsearch is used.

**To Reproduce**
1. Create a resource called "Res1"
2. Go back to / and search for "Res1" or just "1"
3. The search will not show the resource

**Expected behavior**
The search results should include "Res1" / Search should work with numbers

**Comment by setaman** [comment]
@DaTebe @jbuese 
Our custom analyzer with the [`letter`](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-letter-tokenizer.html#analysis-letter-tokenizer) tokenizer eats the numbers!

```
POST _analyze
{
  "tokenizer": "letter",
  "filter": ["lowercase", "asciifolding"],
  "text": ["hello2.pdf"]
}
```

```
{
  "tokens" : [
    {
      "token" : "hello",
      "start_offset" : 0,
      "end_offset" : 5,
      "type" : "word",
      "position" : 0
    },
    {
      "token" : "pdf",
      "start_offset" : 7,
      "end_offset" : 10,
      "type" : "word",
      "position" : 1
    }
  ]
}
```
