### ISSUE TITLE
Add affectedFields to Update Events

### ISSUE THREAD

**Issue by DaTebe** [FraunhoferISST/diva#167]
**Is your feature request related to a problem? Please describe.**
We want to know which metadata has changed when we receive an update event. This allows us to respond to events in a more targeted manner. For example, the recalculation of similarity hashes when keywords change. We don't want to load the entire metadata object or check the history delta. Also there is no connection between history entry and event (maybe we should think of something like a UUID for events?).
 
**Describe the solution you'd like**
When a PATCH request is done, the entity management service should add the affected fields to the event. The field should be inside the _payload_ field. The name should be _affectedFields_. It is a list containing at least the changed root fields.

**Comment by setaman** [comment]
Added `affectedFields` as a property of the `payload.object`. This allows us also to add this field for `attributedTo`, if required in the future. `affectedFields` lists all the root fields from the history delta, **not** from the patch itself. So no worries about redundancy as only true fields changes will be captured.

> `affectedFields` is also populated on the `create` event

This is how the message payload looks like for create/update events:

```js
{
//...
  "object": {
    "id": "resource:uuid:b890e46a-c64e-4766-bebb-466c850fc5df",
    "affectedFields": [
      "title",
      "licenses",
      "modified",
      "description"
    ]
  },
}
```
