### ISSUE TITLE
Users get wrong creator id 

### ISSUE THREAD

**Issue by setaman** [FraunhoferISST/diva#174]
For some reason users are created with wrong creator `id`. Means users do not have own `id` as `creatorId`. For now i don't know where the wrong `creatorId` comes from.  

The most strange thing is that these `creatorId`'s are not know to the system. There are no entities with these `id`'s

**Comment by DaTebe** [comment]
https://github.com/FraunhoferISST/diva/blob/d5edd4e1f0f07494d37621b22c008dd803d99cf8/core/services/entity-management/services/UsersService.js#L10

maybe we send an x-actorid even if we shouldn't ?

**Comment by setaman** [comment]
@DaTebe we actually always send an x-actorid. The question is rather where the wrong id comes from. On the first login (register) we are making a PUT request and the x-actorid should be taken from the Keycloak user. It seems that on this path something goes wrong.

**Comment by DaTebe** [comment]
> we actually always send an x-actorid

That sounds odd. We don't have an id when a user can register by himself. Seems our code does support omitting an x-actorid.

**Comment by setaman** [comment]
the bug comes from this line:
https://github.com/FraunhoferISST/diva/blob/6c67ef483b6bf54502b12442919ca05234ffe852/core/services/entity-management/services/UsersService.js#L8

Just remove the `creatorId` field as we do not use it anymore!
