### ISSUE TITLE
Optimize API calls

### ISSUE THREAD

**Issue by setaman** [FraunhoferISST/diva#19]
**Is your feature request related to a problem? Please describe.**

Web client fetches brings data together from different API's, and that often. For example, on entity history page history entries and the users for each entry a fetched. Under certain circumstances it can lead to the same user being loaded several times (e.g. one user produce many entity updates). That is not dramatic, but inefficient, we can do it better!

**Describe the solution you'd like**

While fetching a list of entities required by another entity, each entity should be fetched only once. We need to add extra sugar to our existing `api.js` module.

**Additional context**
Applies mostly to History and Reviews page (currently)

**Comment by DaTebe** [comment]
@setaman is HTTP caching currently working? Could also save us some full requests.

**Comment by setaman** [comment]
@DaTebe 
on the backend side, we have no explizit mechanisms for API response caching. Browser seem not to cache API request
