### ISSUE TITLE
"PoliciesServiceUnavailable" error on /edges/edge:uuid:[...]

### ISSUE THREAD

**Issue by jbuese** [FraunhoferISST/diva#284]
GET on /edges/edge:uuid:[...] returns a "PoliciesServiceUnavailable" error
https://github.com/FraunhoferISST/diva/blob/main/core/services/entity-management/routes/dataNetwork.js 
`router.get("/edges/:id", dataNetworkController.getEdgeById);` is missing a `.bind`

**Comment by DaTebe** [comment]
@setaman can you confirm?

**Comment by DaTebe** [comment]
@jbuese it did work in DIVA. We need clarification.

**Comment by jbuese** [comment]
I tested the solution in SDaC's entity management, which is practically the same code base. However, I am pretty sure that the `this` in [this line](https://github.com/FraunhoferISST/diva/blob/main/core/services/entity-management/controllers/DataNetworkController.js#L24) of the DataNetworkController depends on the use of `.bind`.
Are you sure that the request for a specific edge has worked before? I would guess that this is a rather unusual request.

**Comment by setaman** [comment]
yeah, there is no reason for `getEdgeById` to work without the `this` binding. Maybe you want to add some basic unit tests in SDaC that just ping the routes and make sure the responses are as expected!?

**Comment by setaman** [comment]
@jbuese what still confusing me is the error message. Actually the route should be responding whit 500 and something like `Unexpected server error`. We should investigate this also.

**Comment by jbuese** [comment]
>  @jbuese what still confusing me is the error message. Actually the route should be responding whit 500 and something like `Unexpected server error`. We should investigate this also. 

Yeah I thought about that too. We actually also found a syntax error in one of SDaCs policies. Now that you mention it, I would suspect that to be the cause for the error message - so the issue title is slightly misguiding.

**Comment by jbuese** [comment]
> yeah, there is no reason for `getEdgeById` to work without the `this` binding. Maybe you want to add some basic unit tests in SDaC that just ping the routes and make sure the responses are as expected!?

For now it works, but unit testing is definitely a todo for the future.

**Comment by setaman** [comment]
> We actually also found a syntax error in one of SDaCs policies.

comes the invalid policy from DIVA? That would explain the error message. On policy enforcement error the BDP would throw 500 that is treated as `PoliciesServiceUnavailable` on EM side, i think.
