### ISSUE TITLE
Entity pagination may produce "false positive" cursor

### ISSUE THREAD

**Issue by setaman** [FraunhoferISST/diva#297]
**Describe the bug**

[The methods that generates next page cursor](https://github.com/FraunhoferISST/diva/blob/main/core/services/entity-management/services/EntityService.js#L61) may create a cursor that should't be created. The reason is that when checking whether another document exists outside the current page, the (possibly defined) filters are not taken into account. That means there may be further documents that however does not meet the filter criteria.

**To Reproduce**

1. Create resources with titles "First resource", "Second resource"
2. Execute GET `/resource?title=First&pageSize=1`
3. The call will return "First resource" and a `cursor` field. 
4. The subsequent page call with the cursor will return an empty result

**Expected behavior**

The method must not create a cursor, if there are nor more subsequent document that match the search query. Simply pass the query to the method:

```js
const createNextCursor = async (currentDoc, collection, query) => {
  const nextDoc = await collection.findOne({
   ...query,
    _id: { $lt: ObjectId(currentDoc._id) },
  });
  return nextDoc ? encodeCursor(`${currentDoc._id}`) : undefined;
};
```

**Your environment(please complete the following information):**

 - DIVA 4

**Additional context**

As i copy-pasted the method to another project and hit the exactly described use case, the bug had made me crazy. So i discovered it.

**Comment by DaTebe** [comment]
@setaman maybe we can have a talk next week?
