### ISSUE TITLE
Interactive references to asset entities in the assets relations graph

### ISSUE THREAD

**Issue by setaman** [FraunhoferISST/diva#43]
We got user feedback, that it would be nice to jump directly to the provided entity using a hyper reference.

**Comment by DaTebe** [comment]
We need to check if this is compatible with the used graph library and it's interaction design.

**Comment by setaman** [comment]
Improved layout with possibility to navigate to selected entity
![Screenshot from 2021-09-07 04-08-48](https://user-images.githubusercontent.com/15034996/132335089-12702072-8914-4285-bf1c-476c0cc70e03.png)
