### ISSUE TITLE
Include Schemata into Schema Registry Container Image

### ISSUE THREAD

**Issue by DaTebe** [FraunhoferISST/diva#7]
**Problem Description:**
We want to simplify our **K8s Deployment**. Currently we would need to claim a persistence storage. We don't want to manage that.

**Desired Solution**
Baking schemata into the container image of our schema registry. We don't want to break local development with and without **docker** here!

**Alternatives considered**

- Schemata stored inside _minIO_. We would need to adjust our _schema registry_.

**Comment by DaTebe** [comment]
@setaman this issue was somehow overlooked. Do you think we should still bake our schemata into the image? We also should consider that users will be able to create custom fields in the future. Could be a problem when we have our schema baked into our image in a static way.

**Comment by setaman** [comment]
@DaTebe the practical usage of schema on runtime should not depend on how they are stored. Especially in the mentioned use case, I don't see any problem as we just move the schemata to other directory.
