### ISSUE TITLE
Delete concept for Entities

### ISSUE THREAD

**Issue by setaman** [FraunhoferISST/diva#72]
**Is your feature request related to a problem? Please describe.**

DIVA has currently no official concept for deletion or deactivation of created entities (e.g. Resources, Assets, Users etc.). The only way is to hard delete the entities directly using corresponding Service API or through the Database

**Describe the solution you'd like**

So we need to provide a concept for deletion/deactivation/archiving. Actually, you don't want to have a _hard delete_ at all. Because deleted data is deleted, can not be recovered. And certainly we should not give such power to our users without proper role management. _Soft delete_ would be the better alternative. But there are also problems and opportunities here.

1. Simple _soft delete_ option:
Mark the entity as deleted and let it in the original Database/collection/index
+ Extend `entity` schema with `deletedAt` time stamp field that marks an entity as deleted
+ Instead of delete update the entity and set the  `deletedAt`
+ Create a special `deleted` history entry
+ Remove the entity from other Databases/collections/entities (on event) and let it only in the MongoDB collection
+ Can be simply restored anytime (just remove the deletion time stamp)

   Disadvantages:

+ Unique key violation. For example it would be not possible to import the same file again, if a soft deleted resource (with the same `uniqueFingerprint`) for this file exists.

  >  As treatment, we can create a unique index depending  on `uniqueFingerprint` + `deletedAt` pair.

+ Soft deleted entities have to be filtered for all possible request

  > Little adjustment in the `common` package

2. _Soft archive_ option:
Move the deleted entities to separate archive

+ Create a archive database and collection (e.g just `archive`)
+ On a normal delete operation:
  - create a archive entry and put it to `archive` database:
      `id` - original id of the entity
      `archivedAt` - time stamp of the archiving 
      `actorId` - `id` of the user/service that archived the entity
      `payload` - JSON-stringified meta data that we want to archive
  - create a special `deleted` history entry
  - remove entity from the original collection
+ Remove the entity from other Databases/collections/entities (on event)
+ Can be restored anytime
+ Admins can easily clean up the archive if needed

**Describe alternatives you've considered**

The described flows are not mandatory, we can do some tweaks depending on concrete requirements and wishes. Additionally to _soft archive_ i would suggest a  _disable_ or _read only_ option to let the entity visible but deactivate any kind of editions. So probably we should have to options:

1. Make entity read only - you can find and see it, but can't edit and profile
2. Delete entity - entity will be _soft archived_ like proposed above, but you can't search it (at least in a legal way). We can left a blank details page that says that it may have been deleted and shows a latest history entries, if any exists.

Also it would make sense to let the history entries or at least a few latest.

**Comment by mspiekermann** [comment]
I would argue to go with the "simple soft delete option" as it seems to me the lesser effort with a suitable solution. 

Nevertheless, the archiving approach is also valid but can maybe added as additional feature in the future (when use cases require this feature or we run into database sizes taht could't be handled otherwise). Thinking of a button for admins like "archive datasets" and then we iterate over all data sources with a deletedAt-stamp and transfer it to a separate archive database.

**Comment by setaman** [comment]
@DaTebe hard delete is obviously the easiest solution and a good one, until an entity is accidentally deleted. Then the requirement for archiving will arise.

We can start with a normal hard delete and see what happens. But "Archive" or "Backup" is an important concept for a system like DIVA, we should keep it in mind,

**Comment by DaTebe** [comment]
That sounds good. Don't get me wrong. We should implement both solutions in our backend. How we propagate it to our client needs to be discussed.

**Comment by setaman** [comment]
As discussed with @DaTebe, we start with _hard delete_, delete all possible traces of the entity (Histories, Search, Assets). Than we will incrementally add archive features, as the need arise.

**Comment by setaman** [comment]
@DaTebe _hard delete_ is implemented in #80

**Comment by setaman** [comment]
@DaTebe 
the resource objects holds the `offerId`, `ruleId` etc. under `dsc.offer`. That data is used to update offers on DSC.
But all the problems, also with MinIO, would disappear with archive feature in the next iteration on this issue. So first we can left this as is

**Comment by DaTebe** [comment]
There was no way to store our uuid inside the dsc, correct?

**Comment by DaTebe** [comment]
I've tested our implementation according to our specification. Everything worked fine for me. Absolutely no hick ups.
