### ISSUE TITLE
Explore Entities in Search

### ISSUE THREAD

**Issue by DaTebe** [FraunhoferISST/diva#97]
It is currently not possible to just scroll through all entities. The user needs a way to just "flow" through the data.

We want to have an "Explore" button that just loads search results without filter query. Maybe then we also need a "normal" search button.

**Comment by setaman** [comment]
@DaTebe 
i would start here with just showing what ever Elasticsearch want by default

**Comment by DaTebe** [comment]
@setaman can you upload a screenshot? Tank you

**Comment by setaman** [comment]
@DaTebe 
The main difference is that now its possible just to scroll down through the results returned from Elasticsearch by default. 

![image](https://user-images.githubusercontent.com/15034996/141990905-aaf22700-d733-40c4-bfe7-4776c03ee332.png)

For the case there is no data:

![image](https://user-images.githubusercontent.com/15034996/141992049-861a26fc-e25d-496c-8743-09bd001bf60d.png)
